<?php
/**
 * Temporary Hostinger compatibility layer for Apostrophe Entertainment.
 *
 * The original website is an ASP.NET Web Pages / Razor application. Hostinger's
 * standard Linux hosting cannot execute that stack, so this file renders the
 * existing Default.cshtml markup with translations from the existing .resx files.
 */

declare(strict_types=1);

$requestedPath = trim((string) parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH), '/');
$language = (($requestedPath === 'fr') || (($_GET['lang'] ?? '') === 'fr')) ? 'fr' : 'en';
$resourceFile = __DIR__ . '/App_GlobalResources/' . ($language === 'fr' ? 'Resource.fr.resx' : 'Resource.resx');
$templateFile = __DIR__ . '/Default.cshtml';

if (!is_file($resourceFile) || !is_file($templateFile)) {
    http_response_code(500);
    exit('Site files are incomplete.');
}

/** @return array<string, string> */
function loadTranslations(string $file): array
{
    libxml_use_internal_errors(true);
    $xml = simplexml_load_file($file, SimpleXMLElement::class, LIBXML_NOCDATA | LIBXML_NONET);

    if ($xml === false) {
        error_log('Unable to parse translation resource: ' . $file);
        return [];
    }

    $translations = [];
    foreach ($xml->data as $item) {
        $attributes = $item->attributes();
        $key = isset($attributes['name']) ? (string) $attributes['name'] : '';
        if ($key !== '') {
            $translations[$key] = (string) $item->value;
        }
    }

    return $translations;
}

$translations = loadTranslations($resourceFile);
$template = file_get_contents($templateFile);

if ($template === false) {
    http_response_code(500);
    exit('Unable to read the site template.');
}

// Skip the server-side Razor bootstrap block and keep the actual HTML document.
$doctypePosition = stripos($template, '<!DOCTYPE html>');
if ($doctypePosition === false) {
    http_response_code(500);
    exit('The site template is invalid.');
}
$template = substr($template, $doctypePosition);

// Remove Razor comments, including the disabled second carousel slide.
$template = preg_replace('/@\*.*?\*@/s', '', $template) ?? $template;

// Reproduce the EN/FR active language classes previously generated by Razor.
$template = preg_replace(
    '/@if\s*\(dilSecimi\s*==\s*"en"\)\s*\{\s*<text>\s*class="aktif"\s*<\/text>\s*\}/',
    $language === 'en' ? 'class="aktif"' : '',
    $template
) ?? $template;
$template = preg_replace(
    '/@if\s*\(dilSecimi\s*==\s*"fr"\)\s*\{\s*<text>\s*class="aktif"\s*<\/text>\s*\}/',
    $language === 'fr' ? 'class="aktif"' : '',
    $template
) ?? $template;

// Replace Razor translation helper calls with values from the original resources.
$template = preg_replace_callback(
    '/@Helper\.dilGetir\("([^"]+)"\)/',
    static function (array $matches) use ($translations): string {
        return $translations[$matches[1]] ?? '';
    },
    $template
) ?? $template;

$template = str_replace('@dilSecimi', $language, $template);
$template = str_replace('src="~/', 'src="/', $template);
$template = str_replace('href="/."', 'href="/' . ($language === 'fr' ? 'fr' : '') . '"', $template);

header('Content-Type: text/html; charset=UTF-8');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: strict-origin-when-cross-origin');

echo $template;
