export type SiteLanguage = 'en' | 'fr';

export type WorkItem = {
  slug: string;
  title: string;
  service: string;
  year?: number;
  summary?: string;
  body?: string[];
  externalLabel?: string;
  externalUrl?: string;
  accent: 'pink' | 'orange' | 'blue' | 'cream' | 'red';
};

export type Testimonial = {
  quote: string;
  name: string;
  role: string;
  company: string;
};

export const workIntro = "A glimpse into the partnerships and campaigns we've had the pleasure of crafting.";
export const testimonialsIntro = 'What our clients say about partnering with us';

export const works: WorkItem[] = [
  { slug: 'eshref-ruya-at-mipcom-2025', title: 'Eshref Ruya at MIPCOM 2025', service: 'PR & Event Management', year: 2025, summary: 'International PR and event management at MIPCOM 2025.', accent: 'pink' },
  { slug: 'ogm-universe-at-mipcom-2025', title: 'OGM Universe at MIPCOM 2025', service: 'PR & Event Management', year: 2025, summary: 'Strategic positioning, media relations and event management for OGM Universe at MIPCOM.', accent: 'blue' },
  { slug: 'apostrophe-entertainment-brand-campaign', title: 'Apostrophe Entertainment Brand Campaign', service: 'Advertising, Creative & Artwork Design', summary: 'A brand-led campaign combining creative direction, advertising and artwork design.', accent: 'orange' },
  { slug: 'timsbi-productions-exclusive-interview-placement', title: 'TIMSBI Productions', service: 'Exclusive Interview Placement', year: 2023, body: ["Apostrophe Entertainment secured an exclusive feature placement for TIMSBI Productions (formerly Tims&B Productions) in Deadline's International Disruptors series, one of the most prestigious editorial formats in the global entertainment industry, spotlighting the boldest and most boundary-pushing voices in film and television.", 'This marked a historic milestone: TIMSBI Productions became the first Turkish production company ever featured in the series, placing Turkish storytelling firmly on the radar of Hollywood and the international entertainment community.', "The placement was the result of targeted media relations strategy, carefully crafted pitching, and Apostrophe's direct access to top-tier global trade press, positioning TIMSBI not just as a regional player, but as a true international force in content creation."], externalLabel: 'Read the full feature on Deadline', externalUrl: 'https://deadline.com/2023/11/international-disruptors-magnificent-century-producers-tims-b-reflect-on-another-love-next-steps-for-company-and-why-turkish-tv-continues-to-punch-above-its-weight-1235575429/', accent: 'cream' },
  { slug: 'indicium-consulting-exclusive-media-announcement', title: 'Indicium Consulting', service: 'Exclusive Media Announcement', year: 2023, body: ['Apostrophe Entertainment secured exclusive coverage on Deadline for the launch of Indicium Consulting and the inaugural SICA Abidjan event, two landmark moments for the African content industry on the global stage.', 'Indicium Consulting, founded by former MIPCOM heavyweights Liliane Da Cruz and Samira Haddi, represents a bold new chapter in African content market development. Apostrophe crafted and executed a targeted PR strategy to ensure the launch received the international trade press attention it deserved, placing the news exclusively with one of the world’s most influential entertainment publications at precisely the right moment.', 'The Deadline piece introduced Indicium Consulting to the global entertainment industry and positioned SICA Abidjan as a significant emerging event on the international content calendar.'], externalLabel: 'Read the full coverage on Deadline', externalUrl: 'https://deadline.com/2023/11/liliane-da-cruz-samira-haddi-launch-indicium-consulting-launch-sica-2023-1235638981/', accent: 'red' },
  { slug: 'timsbi-productions-at-miptv-2023', title: 'TIMSBI Productions at MIPTV 2023', service: 'Exclusive Interview Placement', year: 2023, body: ['Apostrophe Entertainment secured an exclusive interview placement for TIMSBI Productions (formerly Tims&B Productions) in Variety, timed strategically to coincide with MIPTV 2023, the international content market in Cannes.', "The feature put TIMSBI's vision, slate, and creative ambitions in front of the global entertainment industry at one of the year's most critical market moments. The piece spotlighted the launch of Modern Woman alongside the groundbreaking move of taking Magnificent Century - the most-watched Turkish drama in history - into the metaverse, cementing Tims brand’s reputation as a forward-thinking, globally minded production powerhouse.", "Apostrophe's strategic timing and media relations ensured the story landed with maximum impact, reaching international buyers, commissioners, and decision-makers actively attending or following MIPTV."], externalLabel: 'Read the full interview on Variety', externalUrl: 'https://variety.com/2023/digital/global/magnificent-century-tims-b-modern-woman-1235585340/', accent: 'pink' },
  { slug: 'timsbi-productions-advertising-creative-media-planning', title: 'TIMSBI Productions', service: 'Advertising, Creative, Media Planning & Artwork Design', summary: 'Creative and media planning work developed for TIMSBI Productions.', accent: 'orange' },
  { slug: 'another-love-ai-powered-social-engagement-campaign', title: 'Another Love', service: 'AI-Powered Social Engagement Campaign', summary: 'An AI-powered social engagement campaign built around the international momentum of Another Love.', accent: 'blue' },
  { slug: 'zap-tv-istanbul-event', title: 'ZAP TV Istanbul Event', service: 'Event Management', summary: 'Event management for ZAP TV in Istanbul.', accent: 'red' },
  { slug: 'eccho-rights-pr-interview-placement', title: 'Eccho Rights', service: 'PR & Interview Placement', body: ["Apostrophe Entertainment secured an interview placement for Eccho Rights in Episode, positioning the company's Director of Turkish Drama, Handan Özkubat, as a key voice and thought leader in the global entertainment landscape.", "The feature explored the universal appeal of Turkish television storytelling, Eccho Rights' expanding global roster, and the growing international momentum behind their upcoming titles, including I Am Mother and Kara. By placing Handan front and center in a high-profile editorial format, Apostrophe helped elevate Eccho Rights' profile among international buyers, broadcasters, and platforms actively seeking premium Turkish content.", 'The interview served as both a brand-building moment for Eccho Rights and a strategic spotlight on the titles they were actively taking to market, combining thought leadership with targeted content promotion in a single placement.'], externalLabel: 'Read the full interview in Episode Magazine', externalUrl: 'https://episodedergi.com/wp-content/uploads/2023/12/EPISODE-AFT-2023.pdf', accent: 'cream' },
  { slug: 'bitter-lands-in-italy', title: 'Bitter Lands in Italy', service: 'PR & Digital Campaign', externalLabel: 'Read the full interview in Formatbiz', externalUrl: 'https://www.formatbiz.it/dettNews.aspx?id=11554', accent: 'pink' },
];

export const testimonials: Testimonial[] = [
  { quote: 'Collaborating with Apostrophe Entertainment during MIPCOM 2025 was an outstanding experience for OGM UNIVERSE at one of the industry’s most influential global markets. From the strategic positioning of our press conference to the meticulous execution of our MIPCOM celebration, Apostrophe demonstrated a rare combination of high-level strategic communications expertise and refined event management capability. What sets Apostrophe apart is not only its operational excellence but their ability to translate brand vision into meaningful industry presence. Apostrophe operates not merely as a service provider but as a true strategic partner.', name: 'Ekin Karaman Koyuncu', role: 'Global Distribution & Partnership Director', company: 'OGM UNIVERSE' },
  { quote: 'I know Fahriye for almost 10 years now and since the first day I fall in love with her work. She is a keen and trustful partner and a solid, creative and supportive professional and human being, with whom I always count for the success of my projects! I strongly recommend Fahriye Senturk and Apostrophe Entertainment as your right partner.', name: 'Patricia Abreu', role: 'Channel Director', company: 'ZAP TV / Finstar' },
  { quote: 'One of the most important things we value in a solution partner is their commitment to teamwork and parallel dedication to what we value and believe in. Apostrophe’s creative approach and out-of-the-box thinking have significantly contributed to elevating our visibility within the industry throughout these years. Their team consistently goes above and beyond, bringing fresh ideas to the table while keeping our brand’s voice and values front and center.', name: 'Selin Arat', role: 'Director of International Operations', company: 'TIMSBI PRODUCTIONS' },
  { quote: 'What stands out is her ability to quickly understand the essence of a project and translate it into clear and compelling messaging. She approaches PR with strategy in mind. It is not only about visibility, but about timing, audience and long-term positioning. She is responsive, thoughtful and reliable, which makes collaboration smooth and efficient.', name: 'Bo Zhang', role: 'Founder & CEO', company: 'Bolytics' },
  { quote: 'The expertise, knowledge about the Turkish industry, environment, key players within and abroad has always been so valuable. Through the following years, with complete trust on the company expertise, our paths naturally crossed with our own independent companies. Either on PR, Marketing or Event, Apostrophe Entertainment is the company you are lucky to work with!', name: 'Samira Haddi', role: 'Co-Founder, B2B Event and Media Expert', company: 'Indicium Consulting' },
  { quote: 'From the very beginning, their team demonstrated exceptional flexibility, adapting seamlessly to the evolving demands of such a dynamic project. Their ability to pivot and offer creative solutions under tight deadlines was truly impressive. What sets Fahriye and her team apart is their creativity and impressive press network.', name: 'Liliane Da Cruz', role: 'Founder, B2B Event and Media Expert', company: 'Indicium Consulting' },
  { quote: 'Fahriye is an exceptional marketing professional and entrepreneur with unparalleled expertise in the media industry. As the founder of Apostrophe Entertainment, she consistently delivers remarkable results through innovative strategies and a sharp creative vision. Her proven success in the media sector and ability to adapt to diverse markets make her an invaluable partner for companies aiming to elevate their brand on a global scale.', name: 'Handan Özkubat', role: 'Director of Turkish Drama', company: 'Eccho Rights' },
];
