//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Entertainment is a marketing communications agency for companies in the global entertainment &amp; media industry. Our team consists of experts, specifically professionals from the international entertainment content business. With teams in London, Paris and Istanbul; we offer our clients a wide range of integrated marketing communication services, also strategic consultancy, to help their companies prosper, grow and be known in the best possible way worldwide..
        /// </summary>
        internal static string about_icerik {
            get {
                return ResourceManager.GetString("about_icerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en_secim {
            get {
                return ResourceManager.GetString("en_secim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string fields_1 {
            get {
                return ResourceManager.GetString("fields_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Platforms.
        /// </summary>
        internal static string fields_2 {
            get {
                return ResourceManager.GetString("fields_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema.
        /// </summary>
        internal static string fields_3 {
            get {
                return ResourceManager.GetString("fields_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Festivals.
        /// </summary>
        internal static string fields_4 {
            get {
                return ResourceManager.GetString("fields_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Markets.
        /// </summary>
        internal static string fields_5 {
            get {
                return ResourceManager.GetString("fields_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Shows &amp; Awards.
        /// </summary>
        internal static string fields_6 {
            get {
                return ResourceManager.GetString("fields_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Carpet Ceremonies.
        /// </summary>
        internal static string fields_7 {
            get {
                return ResourceManager.GetString("fields_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string footer_adres {
            get {
                return ResourceManager.GetString("footer_adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2023 Apostrophe Entertainment All rights reserved..
        /// </summary>
        internal static string footer_copy {
            get {
                return ResourceManager.GetString("footer_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Entertainment is a marketing communications agency for companies in the global entertainment &amp; media industry..
        /// </summary>
        internal static string footer_kisa {
            get {
                return ResourceManager.GetString("footer_kisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string fr_secim {
            get {
                return ResourceManager.GetString("fr_secim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string geri {
            get {
                return ResourceManager.GetString("geri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ileri {
            get {
                return ResourceManager.GetString("ileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Instagram.
        /// </summary>
        internal static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Linkedin.
        /// </summary>
        internal static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Entertainment.
        /// </summary>
        internal static string logo_title {
            get {
                return ResourceManager.GetString("logo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menu_1 {
            get {
                return ResourceManager.GetString("menu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string menu_2 {
            get {
                return ResourceManager.GetString("menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string menu_3 {
            get {
                return ResourceManager.GetString("menu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string menu_4 {
            get {
                return ResourceManager.GetString("menu_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string menu_5 {
            get {
                return ResourceManager.GetString("menu_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Entertainment is a marketing communications agency for companies in the global entertainment &amp; media industry..
        /// </summary>
        internal static string meta_desc {
            get {
                return ResourceManager.GetString("meta_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Entertainment Marketing Communications Agency.
        /// </summary>
        internal static string meta_title {
            get {
                return ResourceManager.GetString("meta_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategic Communications &amp; PR.
        /// </summary>
        internal static string servis_baslik_1 {
            get {
                return ResourceManager.GetString("servis_baslik_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing.
        /// </summary>
        internal static string servis_baslik_2 {
            get {
                return ResourceManager.GetString("servis_baslik_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B Event Marketing &amp; Management.
        /// </summary>
        internal static string servis_baslik_3 {
            get {
                return ResourceManager.GetString("servis_baslik_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360° Creative Marketing Services.
        /// </summary>
        internal static string servis_baslik_4 {
            get {
                return ResourceManager.GetString("servis_baslik_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategic Consultancy.
        /// </summary>
        internal static string servis_baslik_5 {
            get {
                return ResourceManager.GetString("servis_baslik_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Apostrophe Entertainment, we help our clients to set their goals, analyze their audience, create the key messages and strategies. We believe that a smart Strategic Communication Plan is imperative for any businesses and we start from establishing such plans for our clients as a roadmap for success. Accordingly, we create PR plans and PR campaigns that works well with our clients’ strategies and marketing purposes..
        /// </summary>
        internal static string servis_icerik_1 {
            get {
                return ResourceManager.GetString("servis_icerik_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Apostrophe Entertainment; SEO, Paid Media, Social Media Management, E-mail Marketing are some of the key tactics which we use for establishing integrated marketing communication plans. We implement and manage innovative strategies to market our client’s products and services in the entertainment content business to increase their sales and revenue..
        /// </summary>
        internal static string servis_icerik_2 {
            get {
                return ResourceManager.GetString("servis_icerik_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Apostrophe Entertainment, we design events from the scratch and consult our clients about event marketing and management, specifically for major content markets and festivals. From arranging the company’s attendance to a panel - seminar - conference to private and public content screenings, from organizing special company events as cocktails, private parties, VIP dinners to press &amp; media events and red carpet ceremonies, we provide an extended B2B event management to our clients for them to reach their d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string servis_icerik_3 {
            get {
                return ResourceManager.GetString("servis_icerik_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer our clients an extended creative marketing services which we focus on creating disruptive ideas and building strategies to maximize their marketing impact. Ingenious Content Creation and Concept Design, Advertising, Branding &amp; Design, Photography &amp; Video Production, Social Media Content Production are the services at our agency’s core to  help our clients to stand out..
        /// </summary>
        internal static string servis_icerik_4 {
            get {
                return ResourceManager.GetString("servis_icerik_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Entertainment also provides consultancy for selected clients about content sales &amp; acquisitions, content distribution, co-productions and partnerships, industry trends, and major global entertainment content markets. Having longstanding relationships, a worldwide network and know-how in the field, we are happy to help to the small and medium-sized businesses’ needs in the international entertainment content business..
        /// </summary>
        internal static string servis_icerik_5 {
            get {
                return ResourceManager.GetString("servis_icerik_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Communications Agency for Global Entertainment and Media.
        /// </summary>
        internal static string slider_1 {
            get {
                return ResourceManager.GetString("slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe Telephone.
        /// </summary>
        internal static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
    }
}
